"""Shared non-domain utilities used across the project."""

from src.core.cli import fail, parse_args, require_input_dir, require_tools, require_videos_in
from src.core.config import ENV_VARS, get_config, load_config, reset_config
from src.core.constants import (
    AUDIO_BITRATE,
    AUDIO_EXTENSIONS,
    AUDIO_FILE_EXT,
    AUDIO_FORMATS,
    BITRATE_FALLBACK_BPS,
    EDGE_SILENCE_KEEP_SEC,
    COMPLETED_DIR,
    DEFAULT_MIN_DURATION,
    DEFAULT_NOISE_THRESHOLD,
    DEFAULT_PAD_SEC,
    MAX_PAD_SEC,
    PAD_INCREMENT_SEC,
    SCRIPTS_DIR,
    SIMPLE_DB,
    SIMPLE_MIN_DURATION,
    TARGET_MIN_DURATION,
    TARGET_NOISE_THRESHOLDS_DB,
    TEXT_FILE_EXT,
    TRIM_DECIMAL_PLACES,
    TRIM_TIMESTAMP_EPSILON_SEC,
    VIDEO_EXTENSIONS,
    SNIPPET_DIR,
    TRANSCRIPT_DIR,
    TITLE_DIR,
)
from src.core.filename_sanitizer import sanitize_filename
from src.core.fs_utils import wait_for_file_release
from src.core.paths import (
    create_temp_subdirs,
    get_completed_path,
    get_snippet_path,
    get_title_path,
    get_transcript_path,
    is_completed,
    is_title_done,
    is_transcript_done,
    mark_completed,
    resolve_output_basename,
    sibling_dir,
)

__all__ = [
    "fail",
    "parse_args",
    "require_input_dir",
    "require_tools",
    "require_videos_in",
    "ENV_VARS",
    "get_config",
    "load_config",
    "reset_config",
    "AUDIO_BITRATE",
    "AUDIO_EXTENSIONS",
    "AUDIO_FILE_EXT",
    "AUDIO_FORMATS",
    "BITRATE_FALLBACK_BPS",
    "EDGE_SILENCE_KEEP_SEC",
    "COMPLETED_DIR",
    "DEFAULT_MIN_DURATION",
    "DEFAULT_NOISE_THRESHOLD",
    "DEFAULT_PAD_SEC",
    "MAX_PAD_SEC",
    "PAD_INCREMENT_SEC",
    "SCRIPTS_DIR",
    "SIMPLE_DB",
    "SIMPLE_MIN_DURATION",
    "TARGET_MIN_DURATION",
    "TARGET_NOISE_THRESHOLDS_DB",
    "TEXT_FILE_EXT",
    "TRIM_DECIMAL_PLACES",
    "TRIM_TIMESTAMP_EPSILON_SEC",
    "VIDEO_EXTENSIONS",
    "SNIPPET_DIR",
    "TRANSCRIPT_DIR",
    "TITLE_DIR",
    "sanitize_filename",
    "wait_for_file_release",
    "create_temp_subdirs",
    "get_completed_path",
    "get_snippet_path",
    "get_title_path",
    "get_transcript_path",
    "is_completed",
    "is_title_done",
    "is_transcript_done",
    "mark_completed",
    "resolve_output_basename",
    "sibling_dir",
]
